const mongoose =  require("mongoose");
const user=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
        lowercase:true,
    },
    mobile:{
        type:Number,
        required:true
    },
    dob:{
        type:Date,
        required:true
    },
    password:{
        type:String,
        required:true
    },
   
    singlequantity:{
        type:Number,
        default:1
    },

    address:[
        {
            name:{
                type:String
            },
            phone:{
                type:Number
            },
            houseName:{
                type:String
            },
            city:{
                type:String
            },
          
            pin:{
                type:Number
            },
            distrit:{
                type:String
            },
          
        }
    ],
     
  
    cart:{
            items: [{
                products:{
                    type:mongoose.Schema.Types.ObjectId,
                    ref:"Product"
                },
                quantity:{
                    type:Number,
                    default:0
                },
                price:{
                    type:Number,
                    default:0
                },
                date:{
                    type:Date,
                    default:Date.now
                },
                cartstatus:{
                    type:Boolean,
                    default:true
                }
                }],
                totalprice:{
                    type:Number,
                    default:0
                },
                discount:{
                    type:Number,
                    default:0
                }
        },
    wallet:{
            type:Number,
            default:0
            },
    access:{
        type:Boolean,
        default:true
    },
    liststatus:{
        type:Boolean,
        default:true
    },
    wishlist:[
        {
            product:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"Product"
                }
        }
    ]
})
module.exports = mongoose.model("User",user)